pub enum ByteTarget {
    A, B, C, D, E, H, L, HL, Imm8,
}

pub enum ArithmeticHLTarget {
    BC, DE, HL, SP,
}

pub enum PrefixTarget {
    A, B, C, D, E, H, L, HL,
}

pub enum JumpTest {
    NotZero,
    Zero,
    NotCarry,
    Carry,
    Always,
    HL,
}

pub enum LoadByteTarget {
    A, B, C, D, E, H, L, HLI, HLD, BC, DE, A8, A16, HL, HiC,
}

pub enum LoadByteSource {
    A, B, C, D, E, H, L, D8, HLI, HLD, BC, DE, A8, A16, HL, HiC,
}

pub enum LoadWordTarget {
    BC, DE, HL, SP, A16,
}

pub enum LoadWordSource {
    D16, SP, HL,
}

pub enum LoadType {
    Byte(LoadByteTarget, LoadByteSource),
    Word(LoadWordTarget, LoadWordSource),
}

pub enum StackTarget {
    BC, DE, HL, AF,
}

pub enum IncDecTarget {
    A, B, C, D, E, H, L, BC, DE, HL, SP, HLREF,
}

pub enum Instruction {
    NOP,
    ADD(ByteTarget),
    ADC(ByteTarget),
    SUB(ByteTarget),
    SBC(ByteTarget),
    AND(ByteTarget),
    OR(ByteTarget),
    XOR(ByteTarget),
    CP(ByteTarget),
    INC(IncDecTarget),
    DEC(IncDecTarget),
    ADDHL(ArithmeticHLTarget),
    ADDSP,
    JP(JumpTest),
    JR(JumpTest),
    LD(LoadType),
    PUSH(StackTarget),
    POP(StackTarget),
    CALL(JumpTest),
    RET(JumpTest),
    RETI,
    DI,
    EI,
    LDHL,
    // Accumulator rotates (unprefixed, always clear zero flag)
    RLCA,
    RRCA,
    RLA,
    RRA,
    // Misc
    DAA,
    CPL,
    SCF,
    CCF,
    HALT,
    STOP,
    RST(u8),
    // CB-prefixed
    RLC(PrefixTarget),
    RRC(PrefixTarget),
    RL(PrefixTarget),
    RR(PrefixTarget),
    SLA(PrefixTarget),
    SRA(PrefixTarget),
    SWAP(PrefixTarget),
    SRL(PrefixTarget),
    BIT(u8, PrefixTarget),
    RES(u8, PrefixTarget),
    SET(u8, PrefixTarget),
}

fn prefix_target_from_byte(byte: u8) -> PrefixTarget {
    match byte & 0x07 {
        0 => PrefixTarget::B,
        1 => PrefixTarget::C,
        2 => PrefixTarget::D,
        3 => PrefixTarget::E,
        4 => PrefixTarget::H,
        5 => PrefixTarget::L,
        6 => PrefixTarget::HL,
        7 => PrefixTarget::A,
        _ => unreachable!(),
    }
}

impl Instruction {
    pub fn from_byte(byte: u8, prefixed: bool) -> Option<Instruction> {
        if prefixed {
            Instruction::from_byte_prefixed(byte)
        } else {
            Instruction::from_byte_not_prefixed(byte)
        }
    }

    fn from_byte_prefixed(byte: u8) -> Option<Instruction> {
        let target = prefix_target_from_byte(byte);
        match byte {
            0x00..=0x07 => Some(Instruction::RLC(target)),
            0x08..=0x0F => Some(Instruction::RRC(target)),
            0x10..=0x17 => Some(Instruction::RL(target)),
            0x18..=0x1F => Some(Instruction::RR(target)),
            0x20..=0x27 => Some(Instruction::SLA(target)),
            0x28..=0x2F => Some(Instruction::SRA(target)),
            0x30..=0x37 => Some(Instruction::SWAP(target)),
            0x38..=0x3F => Some(Instruction::SRL(target)),
            0x40..=0x7F => Some(Instruction::BIT((byte >> 3) & 0x07, target)),
            0x80..=0xBF => Some(Instruction::RES((byte >> 3) & 0x07, target)),
            0xC0..=0xFF => Some(Instruction::SET((byte >> 3) & 0x07, target)),
        }
    }

    fn from_byte_not_prefixed(byte: u8) -> Option<Instruction> {
        match byte {
            0x00 => Some(Instruction::NOP),
            0x01 => Some(Instruction::LD(LoadType::Word(LoadWordTarget::BC, LoadWordSource::D16))),
            0x02 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::BC, LoadByteSource::A))),
            0x03 => Some(Instruction::INC(IncDecTarget::BC)),
            0x04 => Some(Instruction::INC(IncDecTarget::B)),
            0x05 => Some(Instruction::DEC(IncDecTarget::B)),
            0x06 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::B, LoadByteSource::D8))),
            0x07 => Some(Instruction::RLCA),
            0x08 => Some(Instruction::LD(LoadType::Word(LoadWordTarget::A16, LoadWordSource::SP))),
            0x09 => Some(Instruction::ADDHL(ArithmeticHLTarget::BC)),
            0x0A => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::BC))),
            0x0B => Some(Instruction::DEC(IncDecTarget::BC)),
            0x0C => Some(Instruction::INC(IncDecTarget::C)),
            0x0D => Some(Instruction::DEC(IncDecTarget::C)),
            0x0E => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::C, LoadByteSource::D8))),
            0x0F => Some(Instruction::RRCA),

            0x10 => Some(Instruction::STOP),
            0x11 => Some(Instruction::LD(LoadType::Word(LoadWordTarget::DE, LoadWordSource::D16))),
            0x12 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::DE, LoadByteSource::A))),
            0x13 => Some(Instruction::INC(IncDecTarget::DE)),
            0x14 => Some(Instruction::INC(IncDecTarget::D)),
            0x15 => Some(Instruction::DEC(IncDecTarget::D)),
            0x16 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::D, LoadByteSource::D8))),
            0x17 => Some(Instruction::RLA),
            0x18 => Some(Instruction::JR(JumpTest::Always)),
            0x19 => Some(Instruction::ADDHL(ArithmeticHLTarget::DE)),
            0x1A => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::DE))),
            0x1B => Some(Instruction::DEC(IncDecTarget::DE)),
            0x1C => Some(Instruction::INC(IncDecTarget::E)),
            0x1D => Some(Instruction::DEC(IncDecTarget::E)),
            0x1E => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::E, LoadByteSource::D8))),
            0x1F => Some(Instruction::RRA),

            0x20 => Some(Instruction::JR(JumpTest::NotZero)),
            0x21 => Some(Instruction::LD(LoadType::Word(LoadWordTarget::HL, LoadWordSource::D16))),
            0x22 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HLI, LoadByteSource::A))),
            0x23 => Some(Instruction::INC(IncDecTarget::HL)),
            0x24 => Some(Instruction::INC(IncDecTarget::H)),
            0x25 => Some(Instruction::DEC(IncDecTarget::H)),
            0x26 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::H, LoadByteSource::D8))),
            0x27 => Some(Instruction::DAA),
            0x28 => Some(Instruction::JR(JumpTest::Zero)),
            0x29 => Some(Instruction::ADDHL(ArithmeticHLTarget::HL)),
            0x2A => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::HLI))),
            0x2B => Some(Instruction::DEC(IncDecTarget::HL)),
            0x2C => Some(Instruction::INC(IncDecTarget::L)),
            0x2D => Some(Instruction::DEC(IncDecTarget::L)),
            0x2E => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::L, LoadByteSource::D8))),
            0x2F => Some(Instruction::CPL),

            0x30 => Some(Instruction::JR(JumpTest::NotCarry)),
            0x31 => Some(Instruction::LD(LoadType::Word(LoadWordTarget::SP, LoadWordSource::D16))),
            0x32 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HLD, LoadByteSource::A))),
            0x33 => Some(Instruction::INC(IncDecTarget::SP)),
            0x34 => Some(Instruction::INC(IncDecTarget::HLREF)),
            0x35 => Some(Instruction::DEC(IncDecTarget::HLREF)),
            0x36 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::D8))),
            0x37 => Some(Instruction::SCF),
            0x38 => Some(Instruction::JR(JumpTest::Carry)),
            0x39 => Some(Instruction::ADDHL(ArithmeticHLTarget::SP)),
            0x3A => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::HLD))),
            0x3B => Some(Instruction::DEC(IncDecTarget::SP)),
            0x3C => Some(Instruction::INC(IncDecTarget::A)),
            0x3D => Some(Instruction::DEC(IncDecTarget::A)),
            0x3E => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::D8))),
            0x3F => Some(Instruction::CCF),

            0x40 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::B, LoadByteSource::B))),
            0x41 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::B, LoadByteSource::C))),
            0x42 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::B, LoadByteSource::D))),
            0x43 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::B, LoadByteSource::E))),
            0x44 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::B, LoadByteSource::H))),
            0x45 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::B, LoadByteSource::L))),
            0x46 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::B, LoadByteSource::HL))),
            0x47 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::B, LoadByteSource::A))),
            0x48 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::C, LoadByteSource::B))),
            0x49 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::C, LoadByteSource::C))),
            0x4A => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::C, LoadByteSource::D))),
            0x4B => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::C, LoadByteSource::E))),
            0x4C => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::C, LoadByteSource::H))),
            0x4D => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::C, LoadByteSource::L))),
            0x4E => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::C, LoadByteSource::HL))),
            0x4F => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::C, LoadByteSource::A))),

            0x50 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::D, LoadByteSource::B))),
            0x51 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::D, LoadByteSource::C))),
            0x52 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::D, LoadByteSource::D))),
            0x53 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::D, LoadByteSource::E))),
            0x54 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::D, LoadByteSource::H))),
            0x55 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::D, LoadByteSource::L))),
            0x56 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::D, LoadByteSource::HL))),
            0x57 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::D, LoadByteSource::A))),
            0x58 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::E, LoadByteSource::B))),
            0x59 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::E, LoadByteSource::C))),
            0x5A => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::E, LoadByteSource::D))),
            0x5B => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::E, LoadByteSource::E))),
            0x5C => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::E, LoadByteSource::H))),
            0x5D => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::E, LoadByteSource::L))),
            0x5E => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::E, LoadByteSource::HL))),
            0x5F => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::E, LoadByteSource::A))),

            0x60 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::H, LoadByteSource::B))),
            0x61 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::H, LoadByteSource::C))),
            0x62 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::H, LoadByteSource::D))),
            0x63 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::H, LoadByteSource::E))),
            0x64 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::H, LoadByteSource::H))),
            0x65 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::H, LoadByteSource::L))),
            0x66 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::H, LoadByteSource::HL))),
            0x67 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::H, LoadByteSource::A))),
            0x68 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::L, LoadByteSource::B))),
            0x69 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::L, LoadByteSource::C))),
            0x6A => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::L, LoadByteSource::D))),
            0x6B => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::L, LoadByteSource::E))),
            0x6C => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::L, LoadByteSource::H))),
            0x6D => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::L, LoadByteSource::L))),
            0x6E => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::L, LoadByteSource::HL))),
            0x6F => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::L, LoadByteSource::A))),

            0x70 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::B))),
            0x71 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::C))),
            0x72 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::D))),
            0x73 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::E))),
            0x74 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::H))),
            0x75 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::L))),
            0x76 => Some(Instruction::HALT),
            0x77 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::A))),
            0x78 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::B))),
            0x79 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::C))),
            0x7A => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::D))),
            0x7B => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::E))),
            0x7C => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::H))),
            0x7D => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::L))),
            0x7E => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::HL))),
            0x7F => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::A))),

            0x80 => Some(Instruction::ADD(ByteTarget::B)),
            0x81 => Some(Instruction::ADD(ByteTarget::C)),
            0x82 => Some(Instruction::ADD(ByteTarget::D)),
            0x83 => Some(Instruction::ADD(ByteTarget::E)),
            0x84 => Some(Instruction::ADD(ByteTarget::H)),
            0x85 => Some(Instruction::ADD(ByteTarget::L)),
            0x86 => Some(Instruction::ADD(ByteTarget::HL)),
            0x87 => Some(Instruction::ADD(ByteTarget::A)),
            0x88 => Some(Instruction::ADC(ByteTarget::B)),
            0x89 => Some(Instruction::ADC(ByteTarget::C)),
            0x8A => Some(Instruction::ADC(ByteTarget::D)),
            0x8B => Some(Instruction::ADC(ByteTarget::E)),
            0x8C => Some(Instruction::ADC(ByteTarget::H)),
            0x8D => Some(Instruction::ADC(ByteTarget::L)),
            0x8E => Some(Instruction::ADC(ByteTarget::HL)),
            0x8F => Some(Instruction::ADC(ByteTarget::A)),

            0x90 => Some(Instruction::SUB(ByteTarget::B)),
            0x91 => Some(Instruction::SUB(ByteTarget::C)),
            0x92 => Some(Instruction::SUB(ByteTarget::D)),
            0x93 => Some(Instruction::SUB(ByteTarget::E)),
            0x94 => Some(Instruction::SUB(ByteTarget::H)),
            0x95 => Some(Instruction::SUB(ByteTarget::L)),
            0x96 => Some(Instruction::SUB(ByteTarget::HL)),
            0x97 => Some(Instruction::SUB(ByteTarget::A)),
            0x98 => Some(Instruction::SBC(ByteTarget::B)),
            0x99 => Some(Instruction::SBC(ByteTarget::C)),
            0x9A => Some(Instruction::SBC(ByteTarget::D)),
            0x9B => Some(Instruction::SBC(ByteTarget::E)),
            0x9C => Some(Instruction::SBC(ByteTarget::H)),
            0x9D => Some(Instruction::SBC(ByteTarget::L)),
            0x9E => Some(Instruction::SBC(ByteTarget::HL)),
            0x9F => Some(Instruction::SBC(ByteTarget::A)),

            0xA0 => Some(Instruction::AND(ByteTarget::B)),
            0xA1 => Some(Instruction::AND(ByteTarget::C)),
            0xA2 => Some(Instruction::AND(ByteTarget::D)),
            0xA3 => Some(Instruction::AND(ByteTarget::E)),
            0xA4 => Some(Instruction::AND(ByteTarget::H)),
            0xA5 => Some(Instruction::AND(ByteTarget::L)),
            0xA6 => Some(Instruction::AND(ByteTarget::HL)),
            0xA7 => Some(Instruction::AND(ByteTarget::A)),
            0xA8 => Some(Instruction::XOR(ByteTarget::B)),
            0xA9 => Some(Instruction::XOR(ByteTarget::C)),
            0xAA => Some(Instruction::XOR(ByteTarget::D)),
            0xAB => Some(Instruction::XOR(ByteTarget::E)),
            0xAC => Some(Instruction::XOR(ByteTarget::H)),
            0xAD => Some(Instruction::XOR(ByteTarget::L)),
            0xAE => Some(Instruction::XOR(ByteTarget::HL)),
            0xAF => Some(Instruction::XOR(ByteTarget::A)),

            0xB0 => Some(Instruction::OR(ByteTarget::B)),
            0xB1 => Some(Instruction::OR(ByteTarget::C)),
            0xB2 => Some(Instruction::OR(ByteTarget::D)),
            0xB3 => Some(Instruction::OR(ByteTarget::E)),
            0xB4 => Some(Instruction::OR(ByteTarget::H)),
            0xB5 => Some(Instruction::OR(ByteTarget::L)),
            0xB6 => Some(Instruction::OR(ByteTarget::HL)),
            0xB7 => Some(Instruction::OR(ByteTarget::A)),
            0xB8 => Some(Instruction::CP(ByteTarget::B)),
            0xB9 => Some(Instruction::CP(ByteTarget::C)),
            0xBA => Some(Instruction::CP(ByteTarget::D)),
            0xBB => Some(Instruction::CP(ByteTarget::E)),
            0xBC => Some(Instruction::CP(ByteTarget::H)),
            0xBD => Some(Instruction::CP(ByteTarget::L)),
            0xBE => Some(Instruction::CP(ByteTarget::HL)),
            0xBF => Some(Instruction::CP(ByteTarget::A)),

            0xC0 => Some(Instruction::RET(JumpTest::NotZero)),
            0xC1 => Some(Instruction::POP(StackTarget::BC)),
            0xC2 => Some(Instruction::JP(JumpTest::NotZero)),
            0xC3 => Some(Instruction::JP(JumpTest::Always)),
            0xC4 => Some(Instruction::CALL(JumpTest::NotZero)),
            0xC5 => Some(Instruction::PUSH(StackTarget::BC)),
            0xC6 => Some(Instruction::ADD(ByteTarget::Imm8)),
            0xC7 => Some(Instruction::RST(0x00)),
            0xC8 => Some(Instruction::RET(JumpTest::Zero)),
            0xC9 => Some(Instruction::RET(JumpTest::Always)),
            0xCA => Some(Instruction::JP(JumpTest::Zero)),
            0xCC => Some(Instruction::CALL(JumpTest::Zero)),
            0xCD => Some(Instruction::CALL(JumpTest::Always)),
            0xCE => Some(Instruction::ADC(ByteTarget::Imm8)),
            0xCF => Some(Instruction::RST(0x08)),

            0xD0 => Some(Instruction::RET(JumpTest::NotCarry)),
            0xD1 => Some(Instruction::POP(StackTarget::DE)),
            0xD2 => Some(Instruction::JP(JumpTest::NotCarry)),
            0xD4 => Some(Instruction::CALL(JumpTest::NotCarry)),
            0xD5 => Some(Instruction::PUSH(StackTarget::DE)),
            0xD6 => Some(Instruction::SUB(ByteTarget::Imm8)),
            0xD7 => Some(Instruction::RST(0x10)),
            0xD8 => Some(Instruction::RET(JumpTest::Carry)),
            0xD9 => Some(Instruction::RETI),
            0xDA => Some(Instruction::JP(JumpTest::Carry)),
            0xDC => Some(Instruction::CALL(JumpTest::Carry)),
            0xDE => Some(Instruction::SBC(ByteTarget::Imm8)),
            0xDF => Some(Instruction::RST(0x18)),

            0xE0 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A8, LoadByteSource::A))),
            0xE1 => Some(Instruction::POP(StackTarget::HL)),
            0xE2 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::HiC, LoadByteSource::A))),
            0xE5 => Some(Instruction::PUSH(StackTarget::HL)),
            0xE6 => Some(Instruction::AND(ByteTarget::Imm8)),
            0xE7 => Some(Instruction::RST(0x20)),
            0xE8 => Some(Instruction::ADDSP),
            0xE9 => Some(Instruction::JP(JumpTest::HL)),
            0xEA => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A16, LoadByteSource::A))),
            0xEE => Some(Instruction::XOR(ByteTarget::Imm8)),
            0xEF => Some(Instruction::RST(0x28)),

            0xF0 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::A8))),
            0xF1 => Some(Instruction::POP(StackTarget::AF)),
            0xF2 => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::HiC))),
            0xF3 => Some(Instruction::DI),
            0xF5 => Some(Instruction::PUSH(StackTarget::AF)),
            0xF6 => Some(Instruction::OR(ByteTarget::Imm8)),
            0xF7 => Some(Instruction::RST(0x30)),
            0xF8 => Some(Instruction::LDHL),
            0xF9 => Some(Instruction::LD(LoadType::Word(LoadWordTarget::SP, LoadWordSource::HL))),
            0xFA => Some(Instruction::LD(LoadType::Byte(LoadByteTarget::A, LoadByteSource::A16))),
            0xFB => Some(Instruction::EI),
            0xFE => Some(Instruction::CP(ByteTarget::Imm8)),
            0xFF => Some(Instruction::RST(0x38)),

            _ => None,
        }
    }
}
